model:
  name: blip2
  load_finetuned: False
  fine_tuned: null
dataset:
  name: ScienceQA
  batch_size: 32
  num_workers: 4
  pin_memory: True

task:
  name: vqa
  device: 0

  # inference
  max_len: 10
  min_len: 1
  num_beams: 5

  seed: 1102
  output_dir: "output"

  evaluate: True
