model:
  name: Blip2
  load_finetuned: False
  fine_tuned: null
  evaluate: True

dataset:
  root: "/mnt/data/lvlm"
  split: "val"
  name: VizWiz
  sample_num: -1
  sample_seed: 1102
  batch_size: 32
  num_workers: 4
  pin_memory: True

task:
  name: vqa
  device: 0

  # inference
  max_len: 10
  min_len: 1
  num_beams: 5

  seed: 1102
  output_dir: "output"
