model:
  name: Blip2
  # model_path: https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/blip2_pretrained_flant5xl.pth
  model_path: ./output/Blip2/ScienceQA/20231113000420/checkpoint_6.pth
  config_path: ./src/models/blip2/config.yaml

dataset:
  root: "/mnt/data/lvlm"
  split:
    train:
      name: "train"
      batch_size: 4
      shuffle: True
      drop_last: True
    eval:
      name: "val"
      batch_size: 16
      shuffle: False
      drop_last: False
  name: VizWiz
  sample_num: -1
  sample_seed: 1102

task:
  name: vqa
  device: 0

  # training
  init_lr: 3e-5
  min_lr: 1e-5
  max_epoch: 7
  weight_decay: 0.02

  # inference
  max_len: 10
  min_len: 1
  num_beams: 5

  seed: 1102
  output_dir: "output"

  prompt: "Question: {} Answer:"
