model:
  max_txt_len: 32
  max_output_txt_len: 32
preprocess:
  vis_processor:
    train:
      name: "blip_image_train"
      image_size: 224
    eval:
      name: "blip_image_eval"
      image_size: 224
  text_processor:
    train:
      name: "blip_question"
    eval:
      name: "blip_question"
